# Generated by Django 4.1.5 on 2023-06-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/None/Noimg.jpg', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='ratings',
            field=models.CharField(default='no rating', max_length=20),
        ),
    ]
